---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(pander)
library(ggplot2)
```



## First look

```{r}
library(myFBr)
path=system.file("extdata","example",package = "myFBr")

  path="~/../Dropbox (DPSS)/lavorincorso/textMining/FB/main/dati/FB/raw_data/LCB1703.zip/"

info=(getInfo(path))
info[c(1:2,6)]="****"

pander(info)

```



## Get the Wall

```{r}
wall=getWall(path)
head(wall)
wall_summ=getWall_summary(wall)
pander(wall_summ)

ddwh=data.frame(wall_summ$freq_ore)
names(ddwh)=c("h","fr")
ggplot(ddwh, aes(x=h, y=fr)) + geom_line(col="red")+
  ggtitle("Attivita' Bacheca per ore del giorno")#+ geom_line(col="cyan")




ddwd=data.frame(wall_summ$freq_giorni)
names(ddwd)=c("h","fr")
ggplot(ddwd, aes(x=h, y=fr)) + geom_point(col="red")+
  ggtitle("Attivita' Bacheca per giorno della settimana")

```



## Get your private chats

```{r}
mess=getMessages(path)
str(mess)
(mess_summ=getMessages_summary(mess))

ddmh=data.frame(mess_summ$freq_ore)
names(ddmh)=c("h","fr")
ggplot(ddmh, aes(x=h, y=fr)) + geom_point(col="red")+
  ggtitle("Messaggi privati per ore del giorno")


ddmd=data.frame(mess_summ$freq_giorni)
names(ddmd)=c("h","fr")
ggplot(ddmd, aes(x=h, y=fr)) + geom_point(col="red")+
  ggtitle("Messaggi privati per giorno della settimana")#+ geom_line(col="cyan")

dd=ddmh
dd$fr_wall=ddwh$fr
names(dd)[2]="fr_mess"
ggplot(data=dd) + geom_point( aes(x=h, y=fr_wall),col="red")+ geom_point(aes(x=h, y=fr_mess),col="cyan")+
  ggtitle("Attività per ora del giorno")+  theme_bw()#+ geom_line(col="cyan")

# res=getAnagrafica(path)
# str(res)
```
